name: Build FAP
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with ufbt (dev SDK)
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        id: build-app
        with:
          sdk-channel: dev          # sau 'release' dacă asta folosești pe Flipper
      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
