name: Build FAP
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Debug listing
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- application.fam ----"
          sed -n '1,200p' application.fam || true
          echo "---- C sources ----"
          ls -la *.c || true

      - name: Setup uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        id: ufbt
        with:
          sdk-channel: release  # pune 'dev' dacă Flipper-ul tău e pe firmware dev

      - name: Build
        run: |
          set -e
          ufbt update
          ufbt list || true      # aici ar trebui să apară "UltralightLockOTP"
          ufbt build

      - name: Upload .fap
        uses: actions/upload-artifact@v4
        with:
          name: fap-${{ steps.ufbt.outputs.suffix }}
          path: "**/*.fap"