name: Build all FAPs (auto-discover)
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uFBT
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.4
        id: ufbt

      - name: Diagnose repo contents
        run: |
          echo "== PWD ==" && pwd
          echo "== Tree (top) ==" && ls -la
          echo "== Find application.fam ==" 
          find "$(pwd)" -type f -name "application.fam" -print | sed 's|^|FOUND: |'

      - name: Build all apps found
        run: |
          set -e
          ROOT="$(pwd)"
          MAPFILE=apps.txt
          # găsește toate directoarele cu application.fam
          find "$ROOT" -type f -name "application.fam" -print > "$MAPFILE"

          if [ ! -s "$MAPFILE" ]; then
            echo "ERROR: niciun application.fam găsit. Verifică numele/locația fișierului."
            exit 2
          fi

          mkdir -p build-collect
          idx=0
          while IFS= read -r fam; do
            dir="$(dirname "$fam")"
            echo "=== [$((++idx))] Building in: $dir"
            ls -la "$dir" || true

            # Forțează canalul SDK să fie ca pe device (schimbă 'release' în 'dev' dacă ai firmware dev)
            (cd "$dir" && ufbt update --channel=release)

            echo "== ufbt list =="
            (cd "$dir" && ufbt list || true)

            echo "== ufbt build =="
            (cd "$dir" && ufbt build)

            # colectează .fap-urile
            find "$dir" -type f -name "*.fap" -print -exec cp -v {} build-collect/ \;
          done < "$MAPFILE"

          echo "== Collected FAPs =="
          ls -la build-collect || true

      - name: Upload FAPs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: faps
          path: build-collect
